apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::441581115197:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1VMWUK1HCYKIK
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-28T04:43:08Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
    manager: vpcLambda
    operation: Update
    time: "2021-07-28T04:43:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1280"
  uid: 29ae879c-bcd4-4493-a24a-324d351aeb4f
